<?php

namespace Database\Seeders;

use App\Models\Department;
use App\Models\User;
use Illuminate\Database\Seeder;

class UserSeeder extends Seeder
{
    public const DEFAULT_PASSWORD = '123456';

    public function run(): void
    {
        $departments = Department::pluck('id', 'code');
        $users = array (
  0 => 
  array (
    'id' => 1,
    'name' => 'Vi Văn Lý',
    'email' => 'admin@gmail.com',
    'employee_code' => 'NH0176',
    'phone' => NULL,
    'address' => NULL,
    'status' => 'working',
    'department_code' => 'IT',
    'locale' => 'vi',
    'position' => 'Trưởng Phòng',
    'role' => 'it',
    'avatar_path' => 'profile-avatars/1/tna67BuxhwlmGIhqKrWlB4WNgRUoKAW5zDLC9knb.jpg',
  ),
  1 => 
  array (
    'id' => 2,
    'name' => 'Nguyễn Khắc Thụ',
    'email' => 'nh0001@gmail.com',
    'employee_code' => 'NH0001',
    'phone' => '0858832242',
    'address' => NULL,
    'status' => 'working',
    'department_code' => 'HCNS',
    'locale' => 'vi',
    'position' => 'Tổng Giám Đốc',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  2 => 
  array (
    'id' => 3,
    'name' => 'Vũ Công Thọ',
    'email' => 'nh0022@gmail.com',
    'employee_code' => 'NH0022',
    'phone' => '0949199860',
    'address' => NULL,
    'status' => 'working',
    'department_code' => 'THAU',
    'locale' => 'vi',
    'position' => 'Giám Đốc',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  3 => 
  array (
    'id' => 4,
    'name' => 'Dương Văn Đại',
    'email' => 'nh0015@gmail.com',
    'employee_code' => 'NH0015',
    'phone' => '0911131869',
    'address' => 'Trung Đồng, xã Hiệp Hòa, tỉnh Bắc Ninh',
    'status' => 'working',
    'department_code' => 'KINH-DOANH',
    'locale' => 'vi',
    'position' => 'Giám Đốc',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  4 => 
  array (
    'id' => 5,
    'name' => 'Đàm Thị Thu Hương',
    'email' => 'nh0089@gmail.com',
    'employee_code' => 'NH0089',
    'phone' => '0936955754',
    'address' => 'Kim Bảng, Phù Khê , Bắc Ninh',
    'status' => 'working',
    'department_code' => 'KE-TOAN',
    'locale' => 'vi',
    'position' => 'Nhân Viên Văn Phòng',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  5 => 
  array (
    'id' => 6,
    'name' => 'Chu Thị Thu Hương',
    'email' => 'nh0104@gmail.com',
    'employee_code' => 'NH0104',
    'phone' => '0394818383',
    'address' => 'Tổ 5, khu phố Hà Tu 4, Phường Hà Tu, Tỉnh Quảng Ninh',
    'status' => 'working',
    'department_code' => 'KE-TOAN',
    'locale' => 'vi',
    'position' => 'Nhân Viên Văn Phòng',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  6 => 
  array (
    'id' => 7,
    'name' => 'Quách Thị Ngọc Lan',
    'email' => 'nh0158@gmail.com',
    'employee_code' => 'NH0158',
    'phone' => '0859910292',
    'address' => 'Thôn Tam Tảo,Xã Tiên Du, Tỉnh Bắc Ninh',
    'status' => 'working',
    'department_code' => 'KE-TOAN',
    'locale' => 'vi',
    'position' => 'Nhân Viên Văn Phòng',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  7 => 
  array (
    'id' => 8,
    'name' => 'Đỗ Viết Đức',
    'email' => 'nh0180@gmail.com',
    'employee_code' => 'NH0180',
    'phone' => '0981922092',
    'address' => 'Thôn Cầu Giữa, Xã Văn Môn, Bắc Ninh',
    'status' => 'working',
    'department_code' => 'KE-TOAN',
    'locale' => 'vi',
    'position' => 'Trưởng Phòng',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  8 => 
  array (
    'id' => 9,
    'name' => 'Nguyễn Thị Hồng',
    'email' => 'nh0059@gmail.com',
    'employee_code' => 'NH0059',
    'phone' => '0366445499',
    'address' => 'Thôn Ngọ Khổng,Xã Xuân Cẩm, Tỉnh Bắc Ninh',
    'status' => 'working',
    'department_code' => 'THAU',
    'locale' => 'vi',
    'position' => 'Nhân Viên Văn Phòng',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  9 => 
  array (
    'id' => 10,
    'name' => 'Trần Anh Tú',
    'email' => 'nh0153@gmail.com',
    'employee_code' => 'NH0153',
    'phone' => '0969667026',
    'address' => 'Lý Nhân, xã Đông Anh, Hà Nội',
    'status' => 'working',
    'department_code' => 'THAU',
    'locale' => 'vi',
    'position' => 'Nhân Viên Văn Phòng',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  10 => 
  array (
    'id' => 11,
    'name' => 'Nguyễn Thúy Thanh',
    'email' => 'nh0111@gmail.com',
    'employee_code' => 'NH0111',
    'phone' => '0383514305',
    'address' => 'Xã Tiên Du, Tỉnh Bắc Ninh',
    'status' => 'working',
    'department_code' => 'KINH-DOANH',
    'locale' => 'vi',
    'position' => 'Nhân Viên Văn Phòng',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  11 => 
  array (
    'id' => 12,
    'name' => 'Trần Thị Loan',
    'email' => 'nh0172@gmail.com',
    'employee_code' => 'NH0172',
    'phone' => '0976374855',
    'address' => 'Thôn Phú Mẫn, Xã Yên Phong, Bắc Ninh',
    'status' => 'working',
    'department_code' => 'KINH-DOANH',
    'locale' => 'vi',
    'position' => 'Nhân Viên Văn Phòng',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  12 => 
  array (
    'id' => 13,
    'name' => 'Lê Thị Diệu Linh',
    'email' => 'nh0156@gmail.com',
    'employee_code' => 'NH0156',
    'phone' => '0327107705',
    'address' => 'Ngô Nội, Yên Phong, Bắc Ninh',
    'status' => 'working',
    'department_code' => 'HCNS',
    'locale' => 'vi',
    'position' => 'Nhân Viên Văn Phòng',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  13 => 
  array (
    'id' => 14,
    'name' => 'Dương Thị Phương Anh',
    'email' => 'nh0171@gmail.com',
    'employee_code' => 'NH0171',
    'phone' => '0964497974',
    'address' => 'Vĩnh Thọ, Phù Khê, Bắc Ninh',
    'status' => 'working',
    'department_code' => 'HCNS',
    'locale' => 'vi',
    'position' => 'Nhân Viên Văn Phòng',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  14 => 
  array (
    'id' => 15,
    'name' => 'Ngô Thị Thoan',
    'email' => 'nh0113@gmail.com',
    'employee_code' => 'NH0113',
    'phone' => '0962799747',
    'address' => NULL,
    'status' => 'working',
    'department_code' => 'HCNS',
    'locale' => 'vi',
    'position' => 'Tạp Vụ',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  15 => 
  array (
    'id' => 16,
    'name' => 'Nguyễn Văn Tuấn',
    'email' => 'nh0110@gmail.com',
    'employee_code' => 'NH0110',
    'phone' => '0982462466',
    'address' => 'Thôn Xuân Lai, xã Đa Phúc, TP Hà Nội',
    'status' => 'working',
    'department_code' => 'HCNS',
    'locale' => 'vi',
    'position' => 'Lái Xe',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  16 => 
  array (
    'id' => 17,
    'name' => 'Trần Văn Vương',
    'email' => 'nh0149@gmail.com',
    'employee_code' => 'NH0149',
    'phone' => '0383590400',
    'address' => NULL,
    'status' => 'working',
    'department_code' => 'HCNS',
    'locale' => 'vi',
    'position' => 'Lái Xe',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  17 => 
  array (
    'id' => 18,
    'name' => 'Trần Ngọc Toàn',
    'email' => 'nh0155@gmail.com',
    'employee_code' => 'NH0155',
    'phone' => '0979329426',
    'address' => 'Thôn Kim Thượng - Xã Đa Phúc - TP Hà Nội',
    'status' => 'working',
    'department_code' => 'HCNS',
    'locale' => 'vi',
    'position' => 'Lái Xe',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  18 => 
  array (
    'id' => 19,
    'name' => 'Mạc Phương Thanh',
    'email' => 'nh0128@gmail.com',
    'employee_code' => 'NH0128',
    'phone' => '0986216136',
    'address' => 'TDP Đáp Cầu 2, Phường Vũ Ninh, Tỉnh Bắc Ninh',
    'status' => 'working',
    'department_code' => 'KE-HOACH',
    'locale' => 'vi',
    'position' => 'Quản Lý Sản Xuất',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  19 => 
  array (
    'id' => 20,
    'name' => 'Nguyễn Ngọc Mai',
    'email' => 'nh0063@gmail.com',
    'employee_code' => 'NH0063',
    'phone' => '0327183434',
    'address' => 'Thôn Tiên Tảo, Xã Đa Phúc, Thành phố Hà Nội',
    'status' => 'working',
    'department_code' => 'SAN-XUAT',
    'locale' => 'vi',
    'position' => 'Quản Lý Sản Xuất',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  20 => 
  array (
    'id' => 21,
    'name' => 'Lê Thanh Bình',
    'email' => 'nh0160@gmail.com',
    'employee_code' => 'NH0160',
    'phone' => '0879839351',
    'address' => 'Thôn Đông Lâu, xã Yên Phong, tỉnh Bắc Ninh',
    'status' => 'working',
    'department_code' => 'NGHIEN-CUU',
    'locale' => 'vi',
    'position' => 'Trưởng Phòng',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  21 => 
  array (
    'id' => 22,
    'name' => 'Nguyễn Thị Thanh Nga',
    'email' => 'nh0170@gmail.com',
    'employee_code' => 'NH0170',
    'phone' => '0359450089',
    'address' => 'Thôn Xuân Giang, Xã Đa Phúc, Thành phố Hà Nội',
    'status' => 'working',
    'department_code' => 'NGHIEN-CUU',
    'locale' => 'vi',
    'position' => 'Nhân Viên Văn Phòng',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  22 => 
  array (
    'id' => 23,
    'name' => 'Nguyễn Quang Thỏa',
    'email' => 'nh0178@gmail.com',
    'employee_code' => 'NH0178',
    'phone' => '0369746623',
    'address' => 'Vinhomes Ocean Park, Gia Lâm, Hà Nội',
    'status' => 'working',
    'department_code' => 'NGHIEN-CUU',
    'locale' => 'vi',
    'position' => 'Nhân Viên Văn Phòng',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  23 => 
  array (
    'id' => 24,
    'name' => 'Đinh Thị Hường',
    'email' => 'nh0045@gmail.com',
    'employee_code' => 'NH0045',
    'phone' => '0976102658',
    'address' => NULL,
    'status' => 'working',
    'department_code' => 'QA',
    'locale' => 'vi',
    'position' => 'Trưởng Phòng',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  24 => 
  array (
    'id' => 25,
    'name' => 'Bùi Thị Thu Phương',
    'email' => 'nh0056@gmail.com',
    'employee_code' => 'NH0056',
    'phone' => '0869308675',
    'address' => 'Ô cách- Yên phong-Bắc Ninh',
    'status' => 'working',
    'department_code' => 'QA',
    'locale' => 'vi',
    'position' => 'Nhân Viên Văn Phòng',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  25 => 
  array (
    'id' => 26,
    'name' => 'Đỗ Thị Nga',
    'email' => 'nh0123@gmail.com',
    'employee_code' => 'NH0123',
    'phone' => '0365277462',
    'address' => 'Yên lãng,Yên trung , Bắc Ninh',
    'status' => 'working',
    'department_code' => 'QA',
    'locale' => 'vi',
    'position' => 'Nhân Viên Văn Phòng',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  26 => 
  array (
    'id' => 27,
    'name' => 'Vũ Thị Ngọc Huyền',
    'email' => 'nh0168@gmail.com',
    'employee_code' => 'NH0168',
    'phone' => '0976027830',
    'address' => 'Đình Cả - Tiên Du - Bắc Ninh',
    'status' => 'working',
    'department_code' => 'QA',
    'locale' => 'vi',
    'position' => 'Nhân Viên Văn Phòng',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  27 => 
  array (
    'id' => 28,
    'name' => 'Ngô Văn Dũng',
    'email' => 'nh0133@gmail.com',
    'employee_code' => 'NH0133',
    'phone' => '0362462099',
    'address' => 'Tổ dân phố Thịnh Lang, phường Từ Sơn, Bắc Ninh',
    'status' => 'working',
    'department_code' => 'QC',
    'locale' => 'vi',
    'position' => 'Trưởng Phòng',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  28 => 
  array (
    'id' => 29,
    'name' => 'Nguyễn Thị Nhường',
    'email' => 'nh0060@gmail.com',
    'employee_code' => 'NH0060',
    'phone' => '0386165050',
    'address' => 'thôn Kim Thượng-xã Đa Phúc-TP Hà Nội',
    'status' => 'working',
    'department_code' => 'QC',
    'locale' => 'vi',
    'position' => 'Nhân Viên Văn Phòng',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  29 => 
  array (
    'id' => 30,
    'name' => 'Phạm Thị Ngọc',
    'email' => 'nh0107@gmail.com',
    'employee_code' => 'NH0107',
    'phone' => '0968622865',
    'address' => 'thôn Tiên Tảo-xã Đa Phúc- TP Hà Nội',
    'status' => 'working',
    'department_code' => 'QC',
    'locale' => 'vi',
    'position' => 'Nhân Viên Văn Phòng',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  30 => 
  array (
    'id' => 31,
    'name' => 'Nguyễn Thị Vân Anh',
    'email' => 'nh0134@gmail.com',
    'employee_code' => 'NH0134',
    'phone' => '0343999263',
    'address' => 'thôn Đình Cả-xã Tiên Du-tỉnh Bắc Ninh',
    'status' => 'working',
    'department_code' => 'QC',
    'locale' => 'vi',
    'position' => 'Nhân Viên Văn Phòng',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  31 => 
  array (
    'id' => 32,
    'name' => 'Nguyễn Thị Nhung',
    'email' => 'nh0152@gmail.com',
    'employee_code' => 'NH0152',
    'phone' => '0982981014',
    'address' => 'thôn Đình Cả-xã Tiên Du-tỉnh Bắc Ninh',
    'status' => 'working',
    'department_code' => 'QC',
    'locale' => 'vi',
    'position' => 'Nhân Viên Văn Phòng',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  32 => 
  array (
    'id' => 33,
    'name' => 'Trần Thanh Nội',
    'email' => 'nh0181@gmail.com',
    'employee_code' => 'NH0181',
    'phone' => '0374658656',
    'address' => 'Thôn Đông, Tam Giang, Bắc Ninh',
    'status' => 'working',
    'department_code' => 'QC',
    'locale' => 'vi',
    'position' => 'Nhân Viên Văn Phòng',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  33 => 
  array (
    'id' => 34,
    'name' => 'Nguyễn Thị Thanh Hương',
    'email' => 'nh0126@gmail.com',
    'employee_code' => 'NH0126',
    'phone' => '0986988022',
    'address' => 'Phù Lộc - Phù Chẩn - Từ Sơn - Bắc Ninh',
    'status' => 'working',
    'department_code' => 'KHO',
    'locale' => 'vi',
    'position' => 'Trưởng Phòng',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  34 => 
  array (
    'id' => 35,
    'name' => 'Nguyễn Thị Chinh',
    'email' => 'nh0034@gmail.com',
    'employee_code' => 'NH0034',
    'phone' => '0396721093',
    'address' => 'Quan Độ - Văn Môn - Bắc Ninh',
    'status' => 'working',
    'department_code' => 'KHO',
    'locale' => 'vi',
    'position' => 'Trưởng Phòng',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  35 => 
  array (
    'id' => 36,
    'name' => 'Vũ Ngọc Liêm',
    'email' => 'nh0146@gmail.com',
    'employee_code' => 'NH0146',
    'phone' => '0327225444',
    'address' => 'Thôn số 1, Xã Hiệp Hòa, Tỉnh Bắc Ninh',
    'status' => 'working',
    'department_code' => 'DU-AN',
    'locale' => 'vi',
    'position' => 'Trưởng Phòng',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  36 => 
  array (
    'id' => 37,
    'name' => 'Ngô Thị Quyền',
    'email' => 'nh0048@gmail.com',
    'employee_code' => 'NH0048',
    'phone' => '0362200035',
    'address' => NULL,
    'status' => 'working',
    'department_code' => 'SAN-XUAT',
    'locale' => 'vi',
    'position' => 'Nhân Viên Sản Xuất',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  37 => 
  array (
    'id' => 38,
    'name' => 'Lại Thị Liên',
    'email' => 'nh0061@gmail.com',
    'employee_code' => 'NH0061',
    'phone' => '0328260839',
    'address' => NULL,
    'status' => 'working',
    'department_code' => 'SAN-XUAT',
    'locale' => 'vi',
    'position' => 'Nhân Viên Sản Xuất',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  38 => 
  array (
    'id' => 39,
    'name' => 'Nguyễn Thị Lan',
    'email' => 'nh0080@gmail.com',
    'employee_code' => 'NH0080',
    'phone' => '0966411039',
    'address' => 'Khu Phố Vĩnh Thọ, Phù Khê, Bắc Ninh',
    'status' => 'working',
    'department_code' => 'SAN-XUAT',
    'locale' => 'vi',
    'position' => 'Nhân Viên Sản Xuất',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  39 => 
  array (
    'id' => 40,
    'name' => 'Dương Thị Hòa',
    'email' => 'nh0084@gmail.com',
    'employee_code' => 'NH0084',
    'phone' => '0962192738',
    'address' => 'khu phố Vĩnh Thọ, phường Phù Khê, Bắc Ninh',
    'status' => 'working',
    'department_code' => 'SAN-XUAT',
    'locale' => 'vi',
    'position' => 'Nhân Viên Sản Xuất',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  40 => 
  array (
    'id' => 41,
    'name' => 'Nguyễn Thị Hữu',
    'email' => 'nh0099@gmail.com',
    'employee_code' => 'NH0099',
    'phone' => NULL,
    'address' => 'Thôn Nghiêm Xá, xã Yên Phong, Bắc Ninh',
    'status' => 'working',
    'department_code' => 'SAN-XUAT',
    'locale' => 'vi',
    'position' => 'Nhân Viên Sản Xuất',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  41 => 
  array (
    'id' => 42,
    'name' => 'Vũ Thị Thơm',
    'email' => 'nh0122@gmail.com',
    'employee_code' => 'NH0122',
    'phone' => '0346886459',
    'address' => 'khu phố Vĩnh Thọ, phường Phù Khê, Bắc Ninh',
    'status' => 'working',
    'department_code' => 'SAN-XUAT',
    'locale' => 'vi',
    'position' => 'Nhân Viên Sản Xuất',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  42 => 
  array (
    'id' => 43,
    'name' => 'Ngô Thị Hảo',
    'email' => 'nh0064@gmail.com',
    'employee_code' => 'NH0064',
    'phone' => '0378582530',
    'address' => NULL,
    'status' => 'working',
    'department_code' => 'SAN-XUAT',
    'locale' => 'vi',
    'position' => 'Nhân Viên Sản Xuất',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  43 => 
  array (
    'id' => 44,
    'name' => 'Ngô Quốc Trí',
    'email' => 'nh0129@gmail.com',
    'employee_code' => 'NH0129',
    'phone' => '0968618951',
    'address' => 'Hương mạc, phù khê,bắc ninh',
    'status' => 'working',
    'department_code' => 'SAN-XUAT',
    'locale' => 'vi',
    'position' => 'Nhân Viên Sản Xuất',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  44 => 
  array (
    'id' => 45,
    'name' => 'Đỗ Thị Châm',
    'email' => 'nh0145@gmail.com',
    'employee_code' => 'NH0145',
    'phone' => '0968347619',
    'address' => NULL,
    'status' => 'working',
    'department_code' => 'SAN-XUAT',
    'locale' => 'vi',
    'position' => 'Nhân Viên Sản Xuất',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  45 => 
  array (
    'id' => 46,
    'name' => 'Nguyễn Thị Hương',
    'email' => 'nh0151@gmail.com',
    'employee_code' => 'NH0151',
    'phone' => '0386627322',
    'address' => 'Thôn Kim Thượng, Xã Đa Phúc, TP Hà Nội',
    'status' => 'working',
    'department_code' => 'SAN-XUAT',
    'locale' => 'vi',
    'position' => 'Nhân Viên Sản Xuất',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  46 => 
  array (
    'id' => 47,
    'name' => 'Nguyễn Thị Lân',
    'email' => 'nh0098@gmail.com',
    'employee_code' => 'NH0098',
    'phone' => '0365968133',
    'address' => NULL,
    'status' => 'working',
    'department_code' => 'SAN-XUAT',
    'locale' => 'vi',
    'position' => 'Nhân Viên Sản Xuất',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  47 => 
  array (
    'id' => 48,
    'name' => 'Dương Thị Loan',
    'email' => 'nh0082@gmail.com',
    'employee_code' => 'NH0082',
    'phone' => NULL,
    'address' => 'Thôn Kim Thượng, Xã Đa Phúc, TP Hà Nội',
    'status' => 'working',
    'department_code' => 'SAN-XUAT',
    'locale' => 'vi',
    'position' => 'Nhân Viên Sản Xuất',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  48 => 
  array (
    'id' => 49,
    'name' => 'Nguyễn Thị Hồi',
    'email' => 'nh0174@gmail.com',
    'employee_code' => 'NH0174',
    'phone' => '0978399016',
    'address' => 'Hà Khê, Xã Thư Lâm, Hà Nội',
    'status' => 'working',
    'department_code' => 'SAN-XUAT',
    'locale' => 'vi',
    'position' => 'Nhân Viên Sản Xuất',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  49 => 
  array (
    'id' => 50,
    'name' => 'Bùi Văn Tưởng',
    'email' => 'nh0175@gmail.com',
    'employee_code' => 'NH0175',
    'phone' => '0358936006',
    'address' => 'Ngô Xã, Yên Phong, Bắc Ninh',
    'status' => 'working',
    'department_code' => 'CO-DIEN',
    'locale' => 'vi',
    'position' => 'Trưởng Phòng',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  50 => 
  array (
    'id' => 51,
    'name' => 'Hầu Sìa Giàng',
    'email' => 'nh0138@gmail.com',
    'employee_code' => 'NH0138',
    'phone' => '0376259045',
    'address' => NULL,
    'status' => 'working',
    'department_code' => 'KHO',
    'locale' => 'vi',
    'position' => 'Nhân Viên Kho',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
  51 => 
  array (
    'id' => 52,
    'name' => 'Vàng Sía Cho',
    'email' => 'nh0139@gmail.com',
    'employee_code' => 'NH0139',
    'phone' => '0383757122',
    'address' => NULL,
    'status' => 'working',
    'department_code' => 'KHO',
    'locale' => 'vi',
    'position' => 'Nhân Viên Kho',
    'role' => 'staff',
    'avatar_path' => NULL,
  ),
);

        foreach ($users as $row) {
            $code = $row['department_code'];
            unset($row['department_code']);
            $row['department_id'] = $code ? ($departments[$code] ?? null) : null;
            $row['password'] = self::DEFAULT_PASSWORD;
            $row['email_verified_at'] = now();

            $user = User::where('employee_code', $row['employee_code'])->first() ?? new User();
            $user->forceFill($row)->save();
        }
    }
}
